<Ball>:
    size: 100, 100
    pos : 20, 400
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size

<Obstacle>:
    id: _ball
    size: 160,320
    pos : 1300, 400
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size

<BallRunner>:
    obstacle: _obstacle
    ball: _ball
    Obstacle:
        id: _obstacle
    Ball:
        id: _ball



